# Docker

# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    # - task: Docker@2
    #   displayName: Build an image
    #   inputs:
    #     command: build
    #     dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    #     tags: |
    #       $(tag)
    # - task: Docker@2
    #   inputs:
    #     containerRegistry: 'docker'
    #     command: 'login'
    # - task: Docker@2
    #   inputs:
    #     containerRegistry: 'docker'
    #     repository: 'docker'
    #     command: 'push'
    - task: Docker@2
      inputs:
        containerRegistry: 'Dockerhub'
        repository: 'poojanakaskar/pythonimage'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
      displayName: 'build and push image'
