# Docker

# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:

    # - task: Docker@2
    #   inputs:
    #     containerRegistry: 'docker'
    #     command: 'login'
    # - task: Docker@2
    #   inputs:
    #     containerRegistry: 'docker'
    #     repository: 'poojanakaskar/flaskimage'
    #     command: 'buildAndPush'
    #     Dockerfile: '**/Dockerfile' 
    - task: Docker@2
      inputs:
        containerRegistry: 'Demodocker'
        repository: 'poojanakaskar/flaskimage'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
    - task: CopyPublishBuildArtifacts@1
      inputs:
        CopyRoot: '$(Agent.BuildDirectory)'
        Contents: '**'
        ArtifactName: 'Test'
        ArtifactType: 'Container'